[package]
name = "osu-classic-switcher"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ctrlc = { version = "3.0", features = ["termination"] }

[build-dependencies]
winres = "0.1.11"